name: game_monopoly
description: A new flutter plugin project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flame: 1.0.0-releasecandidate.13
  flame_audio: 1.0.0-rc.1
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.tikop.game_monopoly
        pluginClass: GameMonopolyPlugin
      ios:
        pluginClass: GameMonopolyPlugin
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/
